### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by ktarasenko**
See each commit for details

### CODE REVIEW

**Comment by lsjwzh** [comment]
O,thanks for your fix!!!

**Comment by lsjwzh** [comment]
But,before seeing your commit,i commit some changes that seems make a conflict. Could you hlep me resolve it ？ Thanks very much！！！

**Comment by ktarasenko** [comment]
fixed. Looks like second pull request is irrelevant already.

**Comment by lsjwzh** [comment]
^_^

**Pull request merged**
