### PR TITLE
Added mLastY param for Action_Down (OnTouchListener) (for getting LastY parameter in action_down listener - local project).

### PR DESCRIPTION
**Pull request by DoronK**
Added mLastY param for Action_Down (OnTouchListener) (for getting LastY parameter in action_down listener - local project).

### CODE REVIEW

**Comment by lsjwzh** [comment]
Why dont  get LastY in OnTouchListener directly??

**Comment by DoronK** [comment]
I cannot get point from ACTION_DOWN when implementing onTouchListener (You were dispatching it on the ViewPager implementation. So i saved the last y (you can add x point in addition) in the Action_Down in the super.

**Comment by DoronK** [comment]
???

**Comment by lsjwzh** [comment]
Thx

**Pull request merged**
